version: "3.3"
services:

  php-fpm:
    image: php:7.4-fpm-alpine
    volumes:
      - ./app:/var/www
    working_dir: /var/www

  nginx:
    build:
      context: .docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    environment:
      - SERVER_NAME=localhost
      - DOCUMENT_ROOT=
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./app:/var/www
    depends_on:
      - php-fpm
